### ISSUE TITLE
Influx 1.2.2-1 influxdb output error

### ISSUE THREAD

**Issue by fenyvesi** [mblackstock/node-red-contrib-influxdb#12] opened 2017-05-10 16:11 UTC
I had a working flow with influx v0.13 and earlier node-red-contrib-influxdb.

I installed a new RPI3 with the actual sw components  **(Influx 1.2.2-1)** and the same flow and all the influxdb output nodes in node-red produce the following error at deploying:

**TypeError: Object function Object() { [native code] } has no method 'assign'**

The function before influxdb node as an example is the following: ( I wouldn't think that the problem is here)

msg.payload = [{
    value: Number(msg.payload)
},
{
	sensor:"moisture"
}];
return msg;

**Comment by mblackstock** [comment] 2017-05-10 17:41
thanks - will have a look.

**Comment by fenyvesi** [comment] 2017-05-16 17:59
Dear Mike,

did you have the opportunity to check the issue?

Thanks.

George

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mblackstock** [comment] 2017-05-16 19:57
I have tried to reproduce it but no luck with my dev environment.  From the error I suspect it's because you are using a different version of node.js - can you tell me what version you are using?

**Comment by mblackstock** [comment] 2017-05-16 21:29
I am not making a call to **Object.assign** in my code, but the newer InfluxDb client that I depend on (5.0.6) uses it.  I managed to see this exact error when I call Object.assign in node.js version 0.10.48, and 0.12.18, but not 4 or later.

So, I think you need to upgrade your version of node.js to 4.x or later.   Hopefully this comes with the newer Raspian image, along with a newer Node-RED, or you can install them manually.  NR 0.16.x needs node.js 4.x or later, and recommends 6.x or later.  If you want to use older versions of node.js, you'll need to use the older version of the influxdb node, but then you may not get compatibility with the newer of influxdb.

Going to close this, since I don't think it's an issue but let me know if you still have problems.

**Closed by mblackstock** 2017-05-16 21:29 UTC

**Comment by fenyvesi** [comment] 2017-05-17 04:18
The installed versions were:
  node-red: 0.15.3
  node.js: 0.10.29

Ater upgrading them everything is fine.

Thank you.
